server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
    name: FullSentence
  datasource:
    url: jdbc:postgresql://usersdb:5432/ejercicio1
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
