server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
    name: FullSentence
  datasource:
    url: jdbc:postgresql://usersdb:5432/ejercicio1
    username: postgres
    password: 1234
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://usersdb:5432/ejercicio1
    username: postgres
    password: 1234
logging:
  level:
    org:
      springframework: ERROR
