spring:
  config:
    activate:
      on-profile: words
server:
  port: 8000
listaPalabras: lista, de, palabras, aleatorias
tipoPalabra: words

---

server:
  port: 8081
listaPalabras: I,You,He,She,It
tipoPalabra: sujeto

---

server:
  port: 8082
listaPalabras: ran,knew,had,saw,bought
tipoPalabra: verbo

---

server:
  port: 8083
listaPalabras: a,the
tipoPalabra: articulo

---

server:
  port: 8084
listaPalabras: reasonable,leaky,suspicious,ordinary,unlikely
tipoPalabra: adjetivo

---

server:
  port: 8085
listaPalabras: boat,book,vote,seat,backpack,partition,groundhog
tipoPalabra: nombre
