server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
spring:
  security:
    user:
      name: root
      password: root
  main:
    banner-mode: off
  application:
    name: ServicioViajes
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://bdservicioviajes:5432/ejercicio4
    username: postgres
    password: 1234
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: test
logging:
  level:
    org:
      springframework: ERROR
