server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: # http://service-registry:8761/eureka
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: ServiceTravel
